# configurazione processi utente
[users]
NOF_USERS=3        # numero di utenti creati all'avvio della simulazione
P_SERV_MIN=10       # probabilità minima (%)
P_SERV_MAX=20       # probabilità massima (%)
N_REQUESTS=6        # numero di richieste di ticket per utente
# configurazione sportelli
[sportelli]
NOF_WORKER_SEATS=6  # numero di sportelli creati all'avvio
# configurazione operatori
[operators]
NOF_WORKERS=6      # numero di operatori creati all'avvio
NOF_PAUSE=1         # numero massimo di pause per operatore
#configurazione ticket
[tickets]
MAX_TICKETS=10 #numero di ticket che possono esistere in contemporanea nella coda di ticket
